[package]
name = "naia-basic-server-demo"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../../"
publish = false
edition = "2018"
license = "MIT OR Apache-2.0"

[features]
use-udp = [ "naia-server/use-udp" ]
use-webrtc = [ "naia-server/use-webrtc" ]
multithread = [ "naia-server/multithread", "naia-basic-demo-shared/multithread" ]

[dependencies]
naia-server = { path = "../../../server" }
naia-default-world = { path = "../../default_world" }
naia-basic-demo-shared = { path = "../shared" }
log = "0.4"
simple_logger = { version = "1.4" }
smol = { version = "1.2.4" }