[workspace]
members = [
    "client",
    "server",
    "shared",
    "derive",
    "demos/basic/server",
    "demos/basic/shared",
    "demos/basic/client/app",
    "demos/basic/client/wasm_bindgen",
    "demos/basic/client/miniquad",
    "demos/dev_http_server",
    "demos/macroquad/server",
    "demos/macroquad/shared",
    "demos/macroquad/client",
    ]