[workspace]
members = [
    "client",
    "server",
    "shared",
    "derive",
    "adapters/hecs/client",
    "adapters/hecs/server",
    "adapters/hecs/shared",
    "demos/basic/server",
    "demos/basic/shared",
    "demos/basic/client/app",
    "demos/basic/client/wasm_bindgen",
    "demos/basic/client/miniquad",
    "demos/dev_http_server",
    "demos/macroquad/server",
    "demos/macroquad/shared",
    "demos/macroquad/client",
    "demos/hecs/server",
    "demos/hecs/shared",
    "demos/hecs/client",
    "demos/bevy/server",
    "demos/bevy/shared",
    "demos/bevy/client",
    ]