[workspace]
members = [
    "client",
    "server",
    "shared",
    "derive",
    "demo/server",
    "demo/shared",
    "demo/client/app",
    "demo/client/wasm_bindgen",
    "demo/client/miniquad",
    "demo/client/miniquad/dev_http_server",
    ]