[package]
name = "naia-bevy-shared"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
homepage = "https://github.com/naia-rs/naia"
repository = "https://github.com/naia-rs/naia"
license = "MIT OR Apache-2.0"
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[features]

[dependencies]
naia-shared = { path = "../../../shared" }
bevy = { version="0.5.0", default-features=false }