[package]
name = "naia-hecs-shared"
version = "0.5.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
description = ""
documentation = "https://docs.rs/naia-client"
homepage = "https://github.com/naia-rs/naia"
repository = "https://github.com/naia-rs/naia"
readme = "../README.md"
keywords = ["wasm", "webrtc", "udp", "networking", "gamedev"]
license = "MIT OR Apache-2.0"
categories = ["network-programming", "game-development", "wasm", "web-programming"]
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[features]
multithread = [ "naia-shared/multithread" ]
wbindgen = [ "naia-shared/wbindgen" ]
mquad = [ "naia-shared/mquad" ]

[dependencies]
naia-shared = { path = "../../../shared" }
hecs = { path = "../../../../Forks/hecs" }
once_cell = "1.8.0"