[package]
name = "naia-server"
version = "0.5.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
description = "A server that uses either UDP or WebRTC communication to send/receive events to/from connected clients, and syncs registered states to clients to whom those states are in-scope."
documentation = "https://docs.rs/naia-server"
homepage = "https://github.com/naia-rs/naia"
repository = "https://github.com/naia-rs/naia"
readme = "../README.md"
keywords = ["webrtc", "udp", "server", "networking", "gamedev"]
license = "MIT OR Apache-2.0"
categories = ["network-programming", "game-development", "wasm", "web-programming"]
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
features = [ "use-webrtc" ]

[features]
use-udp = [ "naia-server-socket/use-udp" ]
use-webrtc = [ "naia-server-socket/use-webrtc" ]
multithread = [ "naia-shared/multithread" ]

[dependencies]
naia-server-socket = { path = "../../naia-socket/server" } #{ version = "0.5.0" }
naia-shared = { version = "0.4.1", path = "../shared" }
log = "0.4"
slotmap = { version = "0.4" }
byteorder = "1.3"
indexmap = "1.4.0"
ring = "0.16.15"
futures-util = { version = "0.3", features = ["sink"] }
async-io = { version = "1.1" }
futures-core = { version = "0.3" }
cfg-if = "0.1.10"