[package]
name = "naia-bevy-demo-shared"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../../"
publish = false
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
naia-shared = { path = "../../../shared", features = ["wbindgen", "multithread"] }
naia-derive = { path = "../../../derive", features = ["multithread"] }
cfg-if = "0.1.10"
log = "0.4"
nanoserde = "0.1.17"