[package]
name = "naia-macroquad-server-demo"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
publish = false
edition = "2018"
license = "MIT OR Apache-2.0"

[features]
use-udp = [ "naia-server/use-udp" ]
use-webrtc = [ "naia-server/use-webrtc" ]

[dependencies]
log = "0.4"
simple_logger = { version = "1.4" }
naia-server = { path = "../../../server" }  #naia-server = { version = "0.5.0" }
naia-macroquad-demo-shared = { path = "../shared" }