[package]
name = "naia-basic-client-demo-mq"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[[bin]]
name = "naia-basic-client-demo-mq"
path = "src/main.rs"

[features]
multithread = [ "naia-basic-client-demo-app/multithread", ]

[dependencies]
cfg-if = "0.1.10"
naia-basic-client-demo-app = { path = "../app", features = [ "mquad" ] }
miniquad = { version = "=0.3.0-alpha.28", features = ["log-impl"] }