[package]
name = "dev_http_server"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "dev_http_server"
path = "src/main.rs"

[dependencies]
actix = "0.10"
actix-codec = { version = "=0.3.0" }
actix-web = { version = "=3.3.1" }
actix-web-actors = "3"
actix-files = "0.3"
awc = "2"
env_logger = "0.8"
futures = "0.3.1"
bytes = "0.5.3"