[package]
name = "naia-empty-world"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
homepage = "https://github.com/naia-rs/naia"
repository = "https://github.com/naia-rs/naia"
edition = "2021"

[features]

[dependencies]
naia-shared = { path = "../../../shared" }