[package]
name = "naia-hecs-server-demo"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../../"
publish = false
edition = "2018"
license = "MIT OR Apache-2.0"

[features]
use-udp = [ "naia-server/use-udp" ]
use-webrtc = [ "naia-server/use-webrtc" ]

[dependencies]
naia-hecs-demo-shared = { path = "../shared" }
naia-server = { path = "../../../server" }
naia-hecs-server = { path = "../../../adapters/hecs/server" }
log = "0.4"
simple_logger = { version = "1.4" }
smol = { version = "1.2.4" }
hecs = { path = "../../../../Forks/hecs" }